package com.team.prezel.core.common.error

enum class AppError {
    UNAUTHORIZED,
    INVALID_REQUEST,
    SERVER_ERROR,
    NOT_FOUND,
    DUPLICATE,
    VOICE_RECOGNITION_FAILED,
    VOICE_ANALYSIS_FAILED,
    SCRIPT_FILE_RECOGNITION_FAILED,
    NETWORK,
    UNKNOWN,
}
