#!/bin/sh
set -e

ROOT_DIR="$(git rev-parse --show-toplevel)"

echo ""
echo "────────── [pre-commit] 시작 ──────────"
echo "ktlintFormat 실행 중..."
"$ROOT_DIR/Prezel/gradlew" -p "$ROOT_DIR/Prezel" ktlintFormat

echo "[pre-commit] 완료"
