# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: ko-KR
reviews:
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  suggested_reviewers: false
  in_progress_fortune: false
  poem: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
