package com.team.prezel.feature.analysis.impl.model

internal enum class AnalysisUiMessage {
    AUTH_EXPIRED,
    ANALYSIS_FAILED,
    SCRIPT_LOAD_FAILED,
    SCRIPT_FILE_LOAD_FAILED,
    NETWORK_FAILED,
    UNKNOWN_FAILED,
    RECORD_AUDIO_PERMISSION_DENIED,
    RECORD_AUDIO_PERMISSION_PERMANENTLY_DENIED,
    RECORDING_START_FAILED,
    RECORDING_STOP_FAILED,
    PLAYBACK_START_FAILED,
}
