build:
    maxIssues: 0

config:
    validation: true

style:
    ReturnCount:
        active: false
    MaxLineLength:
        active: true
        maxLineLength: 150
    MagicNumber:
        active: false
    UnusedPrivateMember:
        ignoreAnnotated:
            - Preview
            - BasicPreview
            - LargeDevicePreview

complexity:
    LongMethod:
        threshold: 50
        ignoreAnnotated:
            - Preview
            - BasicPreview
            - LargeDevicePreview
    NestedBlockDepth:
        threshold: 4
    LongParameterList:
        active: true
        functionThreshold: 10
        constructorThreshold: 10
        ignoreAnnotated:
            - Composable
    TooManyFunctions:
        active: true
        thresholdInFiles: 20
        thresholdInClasses: 15
        thresholdInInterfaces: 12
        thresholdInObjects: 20
        thresholdInEnums: 10
        ignoreAnnotatedFunctions:
            - Preview
            - BasicPreview
            - LargeDevicePreview

naming:
    FunctionNaming:
        active: true
        ignoreAnnotated:
            - Composable
            - Preview
    MatchingDeclarationName:
        active: false

exceptions:
    active: true
    TooGenericExceptionCaught:
        active: false

performance:
    SpreadOperator:
        active: false
